(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DB='zzal-here-db', VER=1, P='photos', F='folders', S='settings';
const ADMIN={id:'admin',password:'admin1234'};
const state={db:null,photos:[],folders:[],view:'all',folder:'all',query:'',selected:new Set(),selectMode:false,isAdmin:sessionStorage.getItem('zzal-admin')==='1',upload:[],viewer:null,pending:null};
const uid=(p='id')=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,9)}`;
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const tags=v=>[...new Set(String(v||'').split(',').map(x=>x.trim()).filter(Boolean))];
const fmt=b=>b<1024?`${b} B`:b<1048576?`${(b/1024).toFixed(1)} KB`:`${(b/1048576).toFixed(1)} MB`;
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(P))d.createObjectStore(P,{keyPath:'id'});if(!d.objectStoreNames.contains(F))d.createObjectStore(F,{keyPath:'id'});if(!d.objectStoreNames.contains(S))d.createObjectStore(S,{keyPath:'key'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function store(n,m='readonly'){return state.db.transaction(n,m).objectStore(n)}
function all(n){return new Promise((res,rej)=>{const r=store(n).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function get(n,k){return new Promise((res,rej)=>{const r=store(n).get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(n,v){return new Promise((res,rej)=>{const r=store(n,'readwrite').put(v);r.onsuccess=()=>res(v);r.onerror=()=>rej(r.error)})}
function del(n,k){return new Promise((res,rej)=>{const r=store(n,'readwrite').delete(k);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function refresh(){state.photos=await all(P);state.folders=await all(F);state.folders.sort((a,b)=>a.createdAt-b.createdAt)}
const active=()=>state.photos.filter(p=>!p.deletedAt), trash=()=>state.photos.filter(p=>p.deletedAt);
const folderName=id=>state.folders.find(f=>f.id===id)?.name||'미분류';
function list(){let a=active();if(state.view==='favorites')a=a.filter(p=>p.favorite);if(state.view==='hot')a.sort((x,y)=>(y.views||0)-(x.views||0)||y.createdAt-x.createdAt);else a.sort((x,y)=>y.createdAt-x.createdAt);if(state.folder==='uncategorized')a=a.filter(p=>!p.folderId);else if(state.folder!=='all')a=a.filter(p=>p.folderId===state.folder);const q=state.query.trim().toLowerCase();if(q)a=a.filter(p=>[p.name,p.memo,...(p.tags||[])].join(' ').toLowerCase().includes(q));return a}
function adminUI(){$$('.admin-only').forEach(e=>e.classList.toggle('hidden',!state.isAdmin));$('#adminBtn').textContent=state.isAdmin?'관리자 로그아웃':'관리자'}
function render(){adminUI();$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));$('#searchInput').value=state.query;$('#selectionBar').classList.toggle('hidden',!state.selectMode);$('#selectedCount').textContent=state.selected.size;if(state.view==='folders')renderFolders();else if(state.view==='settings')renderSettings();else renderGallery()}
function empty(t,d){return `<div class="empty-state"><strong>${esc(t)}</strong><span>${esc(d)}</span></div>`}
function card(p){const u=URL.createObjectURL(p.blob);setTimeout(()=>URL.revokeObjectURL(u),15000);return `<article class="photo-card" data-id="${p.id}">${state.selectMode?`<span class="card-check ${state.selected.has(p.id)?'selected':''}">${state.selected.has(p.id)?'✓':''}</span>`:''}<button class="card-fav ${p.favorite?'on':''}" data-id="${p.id}">${p.favorite?'★':'☆'}</button><img class="photo-thumb" src="${u}" alt="${esc(p.name)}"><div class="photo-info"><div class="photo-name">${esc(p.name)}</div><div class="photo-tags">${p.tags?.length?esc(p.tags.map(x=>'#'+x).join(' ')):'태그 없음'}</div><span class="folder-pill">📁 ${esc(folderName(p.folderId))}</span></div></article>`}
function renderGallery(){const a=list(), names={all:'전체 사진',hot:'HOT',favorites:'즐겨찾기'}, title=state.folder==='all'?(names[state.view]||'전체 사진'):(state.folder==='uncategorized'?'미분류':folderName(state.folder));$('#content').innerHTML=`<div class="gallery-head"><div><h1>${esc(title)}</h1><p>${a.length}장</p></div>${state.selectMode?'':`<button class="btn small" id="enterSelectBtn" ${a.length?'':'disabled'}>선택</button>`}</div>${a.length?`<div class="gallery-grid">${a.map(card).join('')}</div>`:empty('사진이 없습니다.',state.query?'검색 조건을 바꿔 보세요.':'업로드한 사진이 여기에 표시됩니다.')}`;$('#enterSelectBtn')?.addEventListener('click',()=>{state.selectMode=true;render()});$$('.photo-card').forEach(c=>{c.onclick=e=>{if(e.target.closest('.card-fav'))return;state.selectMode?toggle(c.dataset.id):viewer(c.dataset.id)}});$$('.card-fav').forEach(b=>b.onclick=async e=>{e.stopPropagation();if(!state.isAdmin)return toast('관리자 로그인 후 변경할 수 있습니다.');const p=state.photos.find(x=>x.id===b.dataset.id);p.favorite=!p.favorite;await put(P,p);await refresh();render()})}
function renderFolders(){const counts={};active().forEach(p=>counts[p.folderId||'uncategorized']=(counts[p.folderId||'uncategorized']||0)+1);const fs=[{id:'uncategorized',name:'미분류'},...state.folders];$('#content').innerHTML=`<div class="gallery-head"><div><h1>폴더</h1><p>${state.folders.length}개 폴더</p></div>${state.isAdmin?'<button class="btn small" id="folderManageInline">폴더 관리</button>':''}</div><div class="folder-grid">${fs.map(f=>`<button class="folder-card" data-folder="${f.id}"><div class="folder-icon">📁</div><h3>${esc(f.name)}</h3><p>${counts[f.id]||0}장</p></button>`).join('')}</div>`;$$('.folder-card').forEach(b=>b.onclick=()=>{state.view='all';state.folder=b.dataset.folder;render()});$('#folderManageInline')?.addEventListener('click',openFolderManager)}
function renderSettings(){$('#content').innerHTML=`<div class="gallery-head"><div><h1>설정</h1><p>이 브라우저에 저장되는 개인용 설정입니다.</p></div></div><div class="settings-card"><h2>저장소</h2><p>사진은 브라우저 IndexedDB에 저장됩니다. 다른 기기와 자동 동기화되지는 않습니다.</p><div class="setting-row"><strong>전체 사진</strong><span>${active().length}장</span></div><div class="setting-row"><strong>저장 용량</strong><span>${fmt(active().reduce((s,p)=>s+(p.blob?.size||0),0))}</span></div>${state.isAdmin?'<div class="setting-row"><strong>관리자 계정</strong><button class="btn small" id="changeAdmin">변경</button></div><div class="setting-row"><strong>전체 데이터 삭제</strong><button class="btn small danger" id="wipeAll">삭제</button></div>':''}</div>`;$('#changeAdmin')?.addEventListener('click',changeAdmin);$('#wipeAll')?.addEventListener('click',()=>confirmAction('모든 사진과 폴더를 삭제할까요?',wipeAll))}
function toggle(id){state.selected.has(id)?state.selected.delete(id):state.selected.add(id);state.selectMode=true;render()}
function clearSel(){state.selected.clear();state.selectMode=false;render()}
function fillSelect(el,val=''){el.innerHTML=`<option value="">미분류</option>`+state.folders.map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join('');el.value=val||''}
function openUpload(){if(!state.isAdmin)return;state.upload=[];$('#uploadPreview').innerHTML='';$('#uploadCount').textContent='0장';fillSelect($('#uploadFolder'));$('#uploadDialog').showModal()}
function addFiles(files){for(const f of [...files])if(f.type.startsWith('image/'))state.upload.push(f);renderUpload()}
function renderUpload(){const box=$('#uploadPreview');box.innerHTML='';state.upload.forEach((f,i)=>{const u=URL.createObjectURL(f),d=document.createElement('div');d.className='upload-item';d.innerHTML=`<img src="${u}"><button type="button">×</button>`;d.querySelector('button').onclick=()=>{state.upload.splice(i,1);renderUpload()};box.appendChild(d);setTimeout(()=>URL.revokeObjectURL(u),15000)});$('#uploadCount').textContent=`${state.upload.length}장`}
async function doUpload(e){e.preventDefault();if(!state.upload.length)return toast('사진을 선택하세요.');const folderId=$('#uploadFolder').value||null,t=tags($('#uploadTags').value);for(const f of state.upload)await put(P,{id:uid('photo'),name:f.name.replace(/\.[^.]+$/,''),memo:'',tags:t,folderId,favorite:false,views:0,rotation:0,createdAt:Date.now(),deletedAt:null,type:f.type,blob:f});await refresh();state.upload=[];$('#uploadDialog').close();state.view='all';state.folder='all';render();toast('업로드했습니다.')}
async function viewer(id){const p=state.photos.find(x=>x.id===id);if(!p)return;state.viewer=id;p.views=(p.views||0)+1;await put(P,p);const u=URL.createObjectURL(p.blob);$('#viewerImage').src=u;$('#viewerImage').style.transform=`rotate(${p.rotation||0}deg)`;$('#viewerName').textContent=p.name;$('#viewerMeta').textContent=`${folderName(p.folderId)} · 조회 ${p.views}회`;$('#viewerDialog').showModal();setTimeout(()=>URL.revokeObjectURL(u),30000)}
function current(){return state.photos.find(p=>p.id===state.viewer)}
function closeViewer(){$('#viewerDialog').close();state.viewer=null;render()}
function viewerStep(n){const a=list(),i=a.findIndex(p=>p.id===state.viewer);if(i<0||!a.length)return;viewer(a[(i+n+a.length)%a.length].id)}
function download(){const p=current();if(!p)return;const a=document.createElement('a'),u=URL.createObjectURL(p.blob);a.href=u;a.download=p.name||'image';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function rotate(){const p=current();if(!p)return;p.rotation=((p.rotation||0)+90)%360;await put(P,p);$('#viewerImage').style.transform=`rotate(${p.rotation}deg)`}
function openEdit(){const p=current();if(!p)return;$('#editName').value=p.name;$('#editMemo').value=p.memo||'';$('#editTags').value=(p.tags||[]).join(', ');fillSelect($('#editFolder'),p.folderId);$('#editDialog').showModal()}
async function saveEdit(e){e.preventDefault();const p=current();if(!p)return;p.name=$('#editName').value.trim()||p.name;p.memo=$('#editMemo').value.trim();p.tags=tags($('#editTags').value);p.folderId=$('#editFolder').value||null;await put(P,p);await refresh();$('#editDialog').close();closeViewer();toast('수정했습니다.')}
async function deleteCurrent(){const p=current();if(!p)return;p.deletedAt=Date.now();await put(P,p);await refresh();closeViewer();toast('휴지통으로 이동했습니다.')}
async function bulkFav(){for(const id of state.selected){const p=state.photos.find(x=>x.id===id);if(p){p.favorite=true;await put(P,p)}}await refresh();clearSel();toast('즐겨찾기에 추가했습니다.')}
async function bulkDelete(){for(const id of state.selected){const p=state.photos.find(x=>x.id===id);if(p){p.deletedAt=Date.now();await put(P,p)}}await refresh();clearSel();toast('휴지통으로 이동했습니다.')}
function openFolderManager(){renderFolderList();$('#folderDialog').showModal()}
function renderFolderList(){$('#folderList').innerHTML=state.folders.length?state.folders.map(f=>`<div class="folder-manage-row"><div><strong>${esc(f.name)}</strong><div class="count">${active().filter(p=>p.folderId===f.id).length}장</div></div><button class="btn small rename-folder" data-id="${f.id}">이름 변경</button><button class="btn small danger delete-folder" data-id="${f.id}">삭제</button></div>`).join(''):empty('폴더가 없습니다.','새 폴더를 만들어 보세요.');$$('.rename-folder').forEach(b=>b.onclick=()=>renameFolder(b.dataset.id));$$('.delete-folder').forEach(b=>b.onclick=()=>confirmAction('폴더를 삭제할까요? 사진은 미분류로 이동합니다.',()=>deleteFolder(b.dataset.id)))}
async function createFolder(){const name=$('#newFolderName').value.trim();if(!name)return;if(state.folders.some(f=>f.name===name))return toast('같은 이름의 폴더가 있습니다.');await put(F,{id:uid('folder'),name,createdAt:Date.now()});$('#newFolderName').value='';await refresh();renderFolderList();render()}
async function renameFolder(id){const f=state.folders.find(x=>x.id===id),name=prompt('새 폴더 이름',f?.name)?.trim();if(!f||!name)return;f.name=name;await put(F,f);await refresh();renderFolderList();render()}
async function deleteFolder(id){for(const p of state.photos.filter(x=>x.folderId===id)){p.folderId=null;await put(P,p)}await del(F,id);await refresh();renderFolderList();render();toast('폴더를 삭제했습니다.')}
function openMove(){fillSelect($('#folderPickSelect'));$('#folderPickDialog').showModal()}
async function applyMove(e){e.preventDefault();const f=$('#folderPickSelect').value||null;for(const id of state.selected){const p=state.photos.find(x=>x.id===id);if(p){p.folderId=f;await put(P,p)}}await refresh();$('#folderPickDialog').close();clearSel();toast('폴더를 변경했습니다.')}
async function login(e){e.preventDefault();const r=await get(S,'adminCredentials'),c=r?.value||ADMIN;if($('#adminId').value===c.id&&$('#adminPw').value===c.password){state.isAdmin=true;sessionStorage.setItem('zzal-admin','1');$('#adminDialog').close();$('#adminError').classList.add('hidden');render();toast('관리자 모드로 전환했습니다.')}else $('#adminError').classList.remove('hidden')}
function adminAction(){if(state.isAdmin){state.isAdmin=false;sessionStorage.removeItem('zzal-admin');render();toast('로그아웃했습니다.')}else $('#adminDialog').showModal()}
async function changeAdmin(){const r=await get(S,'adminCredentials'),c=r?.value||ADMIN,id=prompt('새 관리자 아이디',c.id)?.trim(),pw=prompt('새 비밀번호 (4자 이상)','');if(!id||!pw||pw.length<4)return;await put(S,{key:'adminCredentials',value:{id,password:pw}});toast('관리자 계정을 변경했습니다.')}
function showStats(){const a=active(),size=a.reduce((s,p)=>s+(p.blob?.size||0),0),fav=a.filter(p=>p.favorite).length;$('#content').innerHTML=`<div class="gallery-head"><div><h1>통계</h1><p>브라우저 로컬 데이터 기준</p></div></div><div class="stats-grid"><div class="stat-card"><div class="label">사진</div><div class="value">${a.length}</div></div><div class="stat-card"><div class="label">폴더</div><div class="value">${state.folders.length}</div></div><div class="stat-card"><div class="label">즐겨찾기</div><div class="value">${fav}</div></div><div class="stat-card"><div class="label">휴지통</div><div class="value">${trash().length}</div></div><div class="stat-card"><div class="label">용량</div><div class="value">${fmt(size)}</div></div></div>`}
function showTrash(){const a=trash().sort((x,y)=>y.deletedAt-x.deletedAt);$('#content').innerHTML=`<div class="gallery-head"><div><h1>휴지통</h1><p>${a.length}장</p></div></div><div class="trash-note"><span>삭제된 사진은 30일 후 자동 삭제됩니다.</span>${state.isAdmin?'<div class="trash-actions"><button class="btn small" id="restoreAll">모두 복구</button><button class="btn small danger" id="emptyTrash">비우기</button></div>':''}</div>${a.length?`<div class="gallery-grid" style="margin-top:12px">${a.map(card).join('')}</div>`:empty('휴지통이 비어 있습니다.','삭제한 사진이 여기에 표시됩니다.')}`;$('#restoreAll')?.addEventListener('click',restoreAll);$('#emptyTrash')?.addEventListener('click',()=>confirmAction('휴지통을 완전히 비울까요?',emptyTrash))}
async function restoreAll(){for(const p of trash()){p.deletedAt=null;await put(P,p)}await refresh();showTrash();toast('복구했습니다.')}
async function emptyTrash(){for(const p of trash())await del(P,p.id);await refresh();showTrash();toast('휴지통을 비웠습니다.')}
async function wipeAll(){for(const p of state.photos)await del(P,p.id);for(const f of state.folders)await del(F,f.id);await refresh();state.view='all';state.folder='all';render();toast('로컬 데이터를 삭제했습니다.')}
function confirmAction(msg,fn){state.pending=fn;$('#confirmText').textContent=msg;$('#confirmDialog').showModal()}
async function confirmSubmit(e){e.preventDefault();const fn=state.pending;state.pending=null;$('#confirmDialog').close();if(fn)await fn()}
async function purge(){const cut=Date.now()-30*86400000;for(const p of state.photos.filter(x=>x.deletedAt&&x.deletedAt<cut))await del(P,p.id);await refresh()}
function bind(){$('#brandBtn').onclick=()=>{state.view='all';state.folder='all';state.query='';render()};$('#adminBtn').onclick=adminAction;$('#uploadBtn').onclick=openUpload;$('#adminForm').onsubmit=login;$('#uploadForm').onsubmit=doUpload;$('#editForm').onsubmit=saveEdit;$('#folderPickForm').onsubmit=applyMove;$('#confirmForm').onsubmit=confirmSubmit;$$('.tab').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.folder='all';state.selected.clear();state.selectMode=false;render()});$('#searchInput').oninput=e=>{state.query=e.target.value;if(!['all','hot','favorites'].includes(state.view))state.view='all';renderGallery()};$('#folderManageBtn').onclick=openFolderManager;$('#trashBtn').onclick=showTrash;$('#statsBtn').onclick=showStats;$$('[data-folder-filter]').forEach(b=>b.onclick=()=>{state.view='all';state.folder=b.dataset.folderFilter;render()});$('#selectAllBtn').onclick=()=>{list().forEach(p=>state.selected.add(p.id));state.selectMode=true;render()};$('#cancelSelectBtn').onclick=clearSel;$('#bulkFavBtn').onclick=bulkFav;$('#bulkMoveBtn').onclick=openMove;$('#bulkDeleteBtn').onclick=()=>confirmAction(`선택한 ${state.selected.size}장을 휴지통으로 이동할까요?`,bulkDelete);$('#bulkZipBtn').onclick=()=>toast('ZIP 다운로드는 다음 버전에서 지원합니다.');$('#pickFilesBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{addFiles(e.target.files);e.target.value=''};const dz=$('#dropzone');['dragenter','dragover'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add('dragover')}));['dragleave','drop'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove('dragover')}));dz.ondrop=e=>addFiles(e.dataTransfer.files);$('#viewerCloseBtn').onclick=closeViewer;$('#viewerPrevBtn').onclick=()=>viewerStep(-1);$('#viewerNextBtn').onclick=()=>viewerStep(1);$('#downloadBtn').onclick=download;$('#rotateBtn').onclick=rotate;$('#editBtn').onclick=openEdit;$('#deleteBtn').onclick=()=>confirmAction('이 사진을 휴지통으로 이동할까요?',deleteCurrent);$('#folderDialogClose').onclick=()=>$('#folderDialog').close();$('#createFolderBtn').onclick=createFolder}
async function init(){state.db=await openDB();await refresh();await purge();bind();render()}
init().catch(e=>{console.error(e);document.body.innerHTML='<div style="padding:40px;font-family:system-ui"><h1>초기화 오류</h1><p>IndexedDB 사용 가능 여부를 확인하세요.</p></div>'});
})();
